"""Tests for git subrepo config command"""

import subprocess
from conftest import assert_gitrepo_field, git_subrepo, assert_output_matches


def test_config(env):
    """Test subrepo config command"""
    # Clone init repo
    subprocess.run(
        ['git', 'clone', str(env.upstream / 'init'), str(env.owner / 'init')],
        check=True,
        capture_output=True,
    )

    gitrepo = env.owner / 'init' / 'doc' / '.gitrepo'

    # Initialize the subrepo
    git_subrepo('init doc', cwd=env.owner / 'init')

    # Test init/doc/.gitrepo file contents
    version = git_subrepo('--version', cwd=env.owner / 'init').stdout.strip()

    assert_gitrepo_field(gitrepo, 'remote', 'none')
    assert_gitrepo_field(gitrepo, 'branch', 'master')
    assert_gitrepo_field(gitrepo, 'commit', '')
    assert_gitrepo_field(gitrepo, 'parent', '')
    assert_gitrepo_field(gitrepo, 'method', 'merge')
    assert_gitrepo_field(gitrepo, 'cmdver', version)

    # Set config option
    result = git_subrepo('config doc method rebase', cwd=env.owner / 'init')
    assert_output_matches(
        result.stdout.strip(),
        "Subrepo 'doc' option 'method' set to 'rebase'.",
        "config set output is correct",
    )

    # Verify config was set
    assert_gitrepo_field(gitrepo, 'remote', 'none')
    assert_gitrepo_field(gitrepo, 'branch', 'master')
    assert_gitrepo_field(gitrepo, 'commit', '')
    assert_gitrepo_field(gitrepo, 'parent', '')
    assert_gitrepo_field(gitrepo, 'method', 'rebase')
    assert_gitrepo_field(gitrepo, 'cmdver', version)

    # Get config option
    result = git_subrepo('config doc method', cwd=env.owner / 'init')
    assert_output_matches(
        result.stdout.strip(),
        "Subrepo 'doc' option 'method' has value 'rebase'.",
        "config get output is correct",
    )

    # Try to set autogenerated field without --force
    output = env.catch('git subrepo config doc branch new', cwd=env.owner / 'init')
    assert_output_matches(
        output,
        "git-subrepo: This option is autogenerated, use '--force' to override.",
        "config autogenerated field error is correct",
    )
