#!/usr/bin/env bash
#
# git-subrepo - Git Submodule Alternative
#
# Copyright 2026 - Thorsten Klein <thorsten.klein.git@gmail.com>
#

# Determine the directory where this script is located
SOURCE_DIR=$(dirname $(realpath "${BASH_SOURCE[0]}"))

# Call the Python implementation only if not being sourced
if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
    "$SOURCE_DIR/git-subrepo.py" "$@"
fi
