#!bash

# DO NOT EDIT. This file generated by pkg/bin/generate-completion.pl.

_git_subrepo() {
    local _opts=" -h --help --version -a --all -A --ALL -b= --branch= -e --edit -f --force -F --fetch -M= --method= --Default -m= --message= -r= --remote= -s --squash -u --update -q --quiet -v --verbose -d --debug -x --DEBUG"
    local subcommands="branch clean clone commit config fetch help init pull push status upgrade version"
    local subdircommands="branch clean commit config fetch pull push status"
    local subcommand="$(__git_find_on_cmdline "$subcommands")"

    if [ -z "$subcommand" ]; then
        # no subcommand yet
        case "$cur" in
        -*)
            __gitcomp "$_opts"
        ;;
        *)
            __gitcomp "$subcommands"
        esac

    else
        case "$cur" in
        -*)
            __gitcomp "$_opts"
            return
        ;;
        esac

        if [[ "$subcommand" == "help" ]]; then
            __gitcomp "$subcommands"
            return
        fi

        local subdircommand="$(__git_find_on_cmdline "$subdircommands")"
        if [ ! -z "$subdircommand" ]; then
            PWD_BAK=$PWD
            GIT_ROOT=$(git rev-parse --show-toplevel)
            cd $GIT_ROOT
            local git_subrepos=`git subrepo status -q`
            git_subrepos_pwd=`for git_subrepo in $git_subrepos; do realpath --relative-to=$PWD_BAK -m $git_subrepo; done`
            cd $PWD_BAK
            __gitcomp "$git_subrepos_pwd"
        fi

    fi
}

